//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCS.Web.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class zh_us {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh_us() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TCS.Web.App_GlobalResources.zh_us", typeof(zh_us).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 账户中心 的本地化字符串。
        /// </summary>
        public static string accountcenter {
            get {
                return ResourceManager.GetString("accountcenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account&amp;Center 的本地化字符串。
        /// </summary>
        public static string accountcenter_us {
            get {
                return ResourceManager.GetString("accountcenter_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 景区地址 的本地化字符串。
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address 的本地化字符串。
        /// </summary>
        public static string address_us {
            get {
                return ResourceManager.GetString("address_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我已阅读并同意 的本地化字符串。
        /// </summary>
        public static string agree {
            get {
                return ResourceManager.GetString("agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 I agreed to 的本地化字符串。
        /// </summary>
        public static string agree_us {
            get {
                return ResourceManager.GetString("agree_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 《旅游投诉网使用协议》 的本地化字符串。
        /// </summary>
        public static string agreement {
            get {
                return ResourceManager.GetString("agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot; the agreement of the LYTSW &quot; 的本地化字符串。
        /// </summary>
        public static string agreement_us {
            get {
                return ResourceManager.GetString("agreement_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部 的本地化字符串。
        /// </summary>
        public static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        public static string all_us {
            get {
                return ResourceManager.GetString("all_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 景区资讯 的本地化字符串。
        /// </summary>
        public static string article {
            get {
                return ResourceManager.GetString("article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Article 的本地化字符串。
        /// </summary>
        public static string article_us {
            get {
                return ResourceManager.GetString("article_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 投诉动态 的本地化字符串。
        /// </summary>
        public static string cmpldynamics {
            get {
                return ResourceManager.GetString("cmpldynamics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 投诉 的本地化字符串。
        /// </summary>
        public static string cmplt {
            get {
                return ResourceManager.GetString("cmplt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 complaint 的本地化字符串。
        /// </summary>
        public static string cmplt_us {
            get {
                return ResourceManager.GetString("cmplt_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cmplt&amp;Dynamics 的本地化字符串。
        /// </summary>
        public static string cmpltdynamics_us {
            get {
                return ResourceManager.GetString("cmpltdynamics_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已回复总量 的本地化字符串。
        /// </summary>
        public static string cmpltresolved {
            get {
                return ResourceManager.GetString("cmpltresolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cmplt&amp;Solved 的本地化字符串。
        /// </summary>
        public static string cmpltresolved_us {
            get {
                return ResourceManager.GetString("cmpltresolved_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 投诉状态 的本地化字符串。
        /// </summary>
        public static string cmpltstatus {
            get {
                return ResourceManager.GetString("cmpltstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        public static string cmpltstatus_us {
            get {
                return ResourceManager.GetString("cmpltstatus_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 投诉时间 的本地化字符串。
        /// </summary>
        public static string cmplttime {
            get {
                return ResourceManager.GetString("cmplttime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit Time 的本地化字符串。
        /// </summary>
        public static string cmplttime_us {
            get {
                return ResourceManager.GetString("cmplttime_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cmplt&amp;Today 的本地化字符串。
        /// </summary>
        public static string cmplttoday_us {
            get {
                return ResourceManager.GetString("cmplttoday_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 投诉总量 的本地化字符串。
        /// </summary>
        public static string cmplttotal {
            get {
                return ResourceManager.GetString("cmplttotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cmplt&amp;Total 的本地化字符串。
        /// </summary>
        public static string cmplttotal_us {
            get {
                return ResourceManager.GetString("cmplttotal_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 投诉类型 的本地化字符串。
        /// </summary>
        public static string cmplttype {
            get {
                return ResourceManager.GetString("cmplttype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tpye 的本地化字符串。
        /// </summary>
        public static string cmplttype_us {
            get {
                return ResourceManager.GetString("cmplttype_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待评价投诉 的本地化字符串。
        /// </summary>
        public static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Commenting 的本地化字符串。
        /// </summary>
        public static string comment_us {
            get {
                return ResourceManager.GetString("comment_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评论 的本地化字符串。
        /// </summary>
        public static string comments {
            get {
                return ResourceManager.GetString("comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 comments 的本地化字符串。
        /// </summary>
        public static string comments_us {
            get {
                return ResourceManager.GetString("comments_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 投诉信息 的本地化字符串。
        /// </summary>
        public static string complaint {
            get {
                return ResourceManager.GetString("complaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 cmplt&amp;Info 的本地化字符串。
        /// </summary>
        public static string complaint_us {
            get {
                return ResourceManager.GetString("complaint_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 投诉标签 的本地化字符串。
        /// </summary>
        public static string complaintlabel {
            get {
                return ResourceManager.GetString("complaintlabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cmplt&amp;Label 的本地化字符串。
        /// </summary>
        public static string complaintlabel_us {
            get {
                return ResourceManager.GetString("complaintlabel_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 咨询 的本地化字符串。
        /// </summary>
        public static string consult {
            get {
                return ResourceManager.GetString("consult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 consult 的本地化字符串。
        /// </summary>
        public static string consult_us {
            get {
                return ResourceManager.GetString("consult_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系电话 的本地化字符串。
        /// </summary>
        public static string contacttel {
            get {
                return ResourceManager.GetString("contacttel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Telephone 的本地化字符串。
        /// </summary>
        public static string contacttel_us {
            get {
                return ResourceManager.GetString("contacttel_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系我们 的本地化字符串。
        /// </summary>
        public static string contactus {
            get {
                return ResourceManager.GetString("contactus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ContactUs 的本地化字符串。
        /// </summary>
        public static string contactus_us {
            get {
                return ResourceManager.GetString("contactus_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认密码 的本地化字符串。
        /// </summary>
        public static string cpassword {
            get {
                return ResourceManager.GetString("cpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConfirmPassword 的本地化字符串。
        /// </summary>
        public static string cpassword_us {
            get {
                return ResourceManager.GetString("cpassword_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评论时间 的本地化字符串。
        /// </summary>
        public static string disctime {
            get {
                return ResourceManager.GetString("disctime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comment Time 的本地化字符串。
        /// </summary>
        public static string disctime_us {
            get {
                return ResourceManager.GetString("disctime_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的评论 的本地化字符串。
        /// </summary>
        public static string discuss {
            get {
                return ResourceManager.GetString("discuss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My Discuss 的本地化字符串。
        /// </summary>
        public static string discuss_us {
            get {
                return ResourceManager.GetString("discuss_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改个人信息 的本地化字符串。
        /// </summary>
        public static string editinfo {
            get {
                return ResourceManager.GetString("editinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Personal Info 的本地化字符串。
        /// </summary>
        public static string editinfo_us {
            get {
                return ResourceManager.GetString("editinfo_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱 的本地化字符串。
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email 的本地化字符串。
        /// </summary>
        public static string email_us {
            get {
                return ResourceManager.GetString("email_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已有账号，请直接 的本地化字符串。
        /// </summary>
        public static string exist {
            get {
                return ResourceManager.GetString("exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Existing account, please direct 的本地化字符串。
        /// </summary>
        public static string exist_us {
            get {
                return ResourceManager.GetString("exist_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 意见反馈 的本地化字符串。
        /// </summary>
        public static string feedback {
            get {
                return ResourceManager.GetString("feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Feedback 的本地化字符串。
        /// </summary>
        public static string feedback_us {
            get {
                return ResourceManager.GetString("feedback_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反馈时间 的本地化字符串。
        /// </summary>
        public static string feedtime {
            get {
                return ResourceManager.GetString("feedtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Feedback Time 的本地化字符串。
        /// </summary>
        public static string feedtime_us {
            get {
                return ResourceManager.GetString("feedtime_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已完结投诉 的本地化字符串。
        /// </summary>
        public static string finished {
            get {
                return ResourceManager.GetString("finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finished 的本地化字符串。
        /// </summary>
        public static string finished_us {
            get {
                return ResourceManager.GetString("finished_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 楼 的本地化字符串。
        /// </summary>
        public static string floor {
            get {
                return ResourceManager.GetString("floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 floor 的本地化字符串。
        /// </summary>
        public static string floor_us {
            get {
                return ResourceManager.GetString("floor_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 忘记密码 的本地化字符串。
        /// </summary>
        public static string forgetpwd {
            get {
                return ResourceManager.GetString("forgetpwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forget  Password 的本地化字符串。
        /// </summary>
        public static string forgetpwd_us {
            get {
                return ResourceManager.GetString("forgetpwd_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 热点投诉 的本地化字符串。
        /// </summary>
        public static string hotcomplaint {
            get {
                return ResourceManager.GetString("hotcomplaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cmplt&amp;Hot 的本地化字符串。
        /// </summary>
        public static string hotcomplaint_us {
            get {
                return ResourceManager.GetString("hotcomplaint_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        public static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index 的本地化字符串。
        /// </summary>
        public static string index_us {
            get {
                return ResourceManager.GetString("index_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息分类 的本地化字符串。
        /// </summary>
        public static string infoclassification {
            get {
                return ResourceManager.GetString("infoclassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info&amp;Classification 的本地化字符串。
        /// </summary>
        public static string infoclassification_us {
            get {
                return ResourceManager.GetString("infoclassification_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最新公告 的本地化字符串。
        /// </summary>
        public static string latestnotice {
            get {
                return ResourceManager.GetString("latestnotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Latest&amp;Notice 的本地化字符串。
        /// </summary>
        public static string latestnotice_us {
            get {
                return ResourceManager.GetString("latestnotice_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登陆 的本地化字符串。
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        public static string login_us {
            get {
                return ResourceManager.GetString("login_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您也可以用以下方式登录： 的本地化字符串。
        /// </summary>
        public static string loginway {
            get {
                return ResourceManager.GetString("loginway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can also login in the following way: 的本地化字符串。
        /// </summary>
        public static string loginway_us {
            get {
                return ResourceManager.GetString("loginway_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上次登录时间 的本地化字符串。
        /// </summary>
        public static string logontime {
            get {
                return ResourceManager.GetString("logontime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last logon time 的本地化字符串。
        /// </summary>
        public static string logontime_us {
            get {
                return ResourceManager.GetString("logontime_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注销 的本地化字符串。
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logout 的本地化字符串。
        /// </summary>
        public static string logout_us {
            get {
                return ResourceManager.GetString("logout_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本月 的本地化字符串。
        /// </summary>
        public static string month {
            get {
                return ResourceManager.GetString("month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Month 的本地化字符串。
        /// </summary>
        public static string month_us {
            get {
                return ResourceManager.GetString("month_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更多 的本地化字符串。
        /// </summary>
        public static string more {
            get {
                return ResourceManager.GetString("more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More 的本地化字符串。
        /// </summary>
        public static string more_us {
            get {
                return ResourceManager.GetString("more_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的投诉 的本地化字符串。
        /// </summary>
        public static string mycmplt {
            get {
                return ResourceManager.GetString("mycmplt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        public static string mycmplt_us {
            get {
                return ResourceManager.GetString("mycmplt_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的反馈 的本地化字符串。
        /// </summary>
        public static string myfeedback {
            get {
                return ResourceManager.GetString("myfeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My Feedback 的本地化字符串。
        /// </summary>
        public static string myfeedback_us {
            get {
                return ResourceManager.GetString("myfeedback_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 昵称 的本地化字符串。
        /// </summary>
        public static string nickname {
            get {
                return ResourceManager.GetString("nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NickName 的本地化字符串。
        /// </summary>
        public static string nickname_us {
            get {
                return ResourceManager.GetString("nickname_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还没有账号，请直接 的本地化字符串。
        /// </summary>
        public static string noexist {
            get {
                return ResourceManager.GetString("noexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If no account, please directly 的本地化字符串。
        /// </summary>
        public static string noexist_us {
            get {
                return ResourceManager.GetString("noexist_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 投诉须知 的本地化字符串。
        /// </summary>
        public static string notice {
            get {
                return ResourceManager.GetString("notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 notice 的本地化字符串。
        /// </summary>
        public static string notice_us {
            get {
                return ResourceManager.GetString("notice_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 景区回复 的本地化字符串。
        /// </summary>
        public static string officalresponse {
            get {
                return ResourceManager.GetString("officalresponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tourism Response 的本地化字符串。
        /// </summary>
        public static string officalresponse_us {
            get {
                return ResourceManager.GetString("officalresponse_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 password 的本地化字符串。
        /// </summary>
        public static string password_us {
            get {
                return ResourceManager.GetString("password_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个人信息 的本地化字符串。
        /// </summary>
        public static string personalinfo {
            get {
                return ResourceManager.GetString("personalinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info&amp;Personal 的本地化字符串。
        /// </summary>
        public static string personalinfo_us {
            get {
                return ResourceManager.GetString("personalinfo_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待处理投诉 的本地化字符串。
        /// </summary>
        public static string processing {
            get {
                return ResourceManager.GetString("processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processing 的本地化字符串。
        /// </summary>
        public static string processing_us {
            get {
                return ResourceManager.GetString("processing_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发表投诉 的本地化字符串。
        /// </summary>
        public static string publish {
            get {
                return ResourceManager.GetString("publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Publish 的本地化字符串。
        /// </summary>
        public static string publish_us {
            get {
                return ResourceManager.GetString("publish_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 真实姓名 的本地化字符串。
        /// </summary>
        public static string realname {
            get {
                return ResourceManager.GetString("realname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RealName 的本地化字符串。
        /// </summary>
        public static string realname_us {
            get {
                return ResourceManager.GetString("realname_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册 的本地化字符串。
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Register 的本地化字符串。
        /// </summary>
        public static string register_us {
            get {
                return ResourceManager.GetString("register_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册时间 的本地化字符串。
        /// </summary>
        public static string regtime {
            get {
                return ResourceManager.GetString("regtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RegTime 的本地化字符串。
        /// </summary>
        public static string regtime_us {
            get {
                return ResourceManager.GetString("regtime_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记住密码 的本地化字符串。
        /// </summary>
        public static string remember {
            get {
                return ResourceManager.GetString("remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remember Me 的本地化字符串。
        /// </summary>
        public static string remember_us {
            get {
                return ResourceManager.GetString("remember_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的回信 的本地化字符串。
        /// </summary>
        public static string reply {
            get {
                return ResourceManager.GetString("reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reply 的本地化字符串。
        /// </summary>
        public static string reply_us {
            get {
                return ResourceManager.GetString("reply_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回复时间 的本地化字符串。
        /// </summary>
        public static string responsetime {
            get {
                return ResourceManager.GetString("responsetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Response Time 的本地化字符串。
        /// </summary>
        public static string responsetime_us {
            get {
                return ResourceManager.GetString("responsetime_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解决满意度 的本地化字符串。
        /// </summary>
        public static string satisfaction {
            get {
                return ResourceManager.GetString("satisfaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Satisfaction 的本地化字符串。
        /// </summary>
        public static string satisfaction_us {
            get {
                return ResourceManager.GetString("satisfaction_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 满意度评分 的本地化字符串。
        /// </summary>
        public static string score {
            get {
                return ResourceManager.GetString("score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Score 的本地化字符串。
        /// </summary>
        public static string score_us {
            get {
                return ResourceManager.GetString("score_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 性别 的本地化字符串。
        /// </summary>
        public static string sex {
            get {
                return ResourceManager.GetString("sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sex 的本地化字符串。
        /// </summary>
        public static string sex_us {
            get {
                return ResourceManager.GetString("sex_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 投诉统计 的本地化字符串。
        /// </summary>
        public static string statistics {
            get {
                return ResourceManager.GetString("statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Statistics 的本地化字符串。
        /// </summary>
        public static string statistics_us {
            get {
                return ResourceManager.GetString("statistics_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话 的本地化字符串。
        /// </summary>
        public static string tel {
            get {
                return ResourceManager.GetString("tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tel 的本地化字符串。
        /// </summary>
        public static string tel_us {
            get {
                return ResourceManager.GetString("tel_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        public static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TIME 的本地化字符串。
        /// </summary>
        public static string time_us {
            get {
                return ResourceManager.GetString("time_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 的本地化字符串。
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TITLE 的本地化字符串。
        /// </summary>
        public static string title_us {
            get {
                return ResourceManager.GetString("title_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 去评价 的本地化字符串。
        /// </summary>
        public static string tocomment {
            get {
                return ResourceManager.GetString("tocomment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go to comment 的本地化字符串。
        /// </summary>
        public static string tocomment_us {
            get {
                return ResourceManager.GetString("tocomment_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 今日投诉 的本地化字符串。
        /// </summary>
        public static string today {
            get {
                return ResourceManager.GetString("today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总数 的本地化字符串。
        /// </summary>
        public static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total 的本地化字符串。
        /// </summary>
        public static string total_us {
            get {
                return ResourceManager.GetString("total_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TYPE 的本地化字符串。
        /// </summary>
        public static string type_us {
            get {
                return ResourceManager.GetString("type_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 投诉人 的本地化字符串。
        /// </summary>
        public static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 USER 的本地化字符串。
        /// </summary>
        public static string user_us {
            get {
                return ResourceManager.GetString("user_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个人中心 的本地化字符串。
        /// </summary>
        public static string usercenter {
            get {
                return ResourceManager.GetString("usercenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UserCenter 的本地化字符串。
        /// </summary>
        public static string usercenter_us {
            get {
                return ResourceManager.GetString("usercenter_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户登录 的本地化字符串。
        /// </summary>
        public static string userlogin {
            get {
                return ResourceManager.GetString("userlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        public static string userlogin_us {
            get {
                return ResourceManager.GetString("userlogin_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account 的本地化字符串。
        /// </summary>
        public static string username_us {
            get {
                return ResourceManager.GetString("username_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户注册 的本地化字符串。
        /// </summary>
        public static string userrigister {
            get {
                return ResourceManager.GetString("userrigister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rigister 的本地化字符串。
        /// </summary>
        public static string userrigister_us {
            get {
                return ResourceManager.GetString("userrigister_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码 的本地化字符串。
        /// </summary>
        public static string validcode {
            get {
                return ResourceManager.GetString("validcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ValidCode 的本地化字符串。
        /// </summary>
        public static string validcode_us {
            get {
                return ResourceManager.GetString("validcode_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看详情 的本地化字符串。
        /// </summary>
        public static string viewdetails {
            get {
                return ResourceManager.GetString("viewdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View details 的本地化字符串。
        /// </summary>
        public static string viewdetails_us {
            get {
                return ResourceManager.GetString("viewdetails_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎来到七星景区旅游投诉网 的本地化字符串。
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome to Qi Xing LYTSW 的本地化字符串。
        /// </summary>
        public static string welcome_us {
            get {
                return ResourceManager.GetString("welcome_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 今年 的本地化字符串。
        /// </summary>
        public static string year {
            get {
                return ResourceManager.GetString("year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Year 的本地化字符串。
        /// </summary>
        public static string year_us {
            get {
                return ResourceManager.GetString("year_us", resourceCulture);
            }
        }
    }
}
